name: Update Submodules

on:
  schedule:
    - cron: '0 3 * * *'   # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive        # pulls submodules too
          token: ${{ secrets.GITHUB_TOKEN }}  # 🔑 use the repo token
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules to latest commit on their branch
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote
          git add .
          git commit -m "chore: update submodules to latest" || echo "No changes to commit"

      - name: Push changes back to main
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Mummanajagadeesh/ViSiON.git HEAD:main
